spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-m5ee476bu350735gjeo.mysql.rds.aliyuncs.com:3306/first_smart_campus?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: XuNiit_#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #show-sql: true
  #redis配置数据
  redis:
    database: 0
    port: 6379
    host: 101.37.31.188
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.soft1851.smart.campus.model.entity
  global-config:
    db-config:
      # 主键策略 auto主键自增，input用户输入id，id_worker全局唯一的数字id，UUID全局唯一的UUID
      id-type: auto
      # 字段策略
      field-strategy: not_empty
      # 开启驼峰式
      table-underline: true
#      db_type: mysql